In [1]:
import numpy as np
import time

def gauss_seidel_matrices(A, b, x0, tol):
    D = np.diag(np.diag(A))

    U = D - np.triu(A)

    L = D - np.tril(A)

    T_g = np.dot(np.linalg.inv(D - L), U)

    C_g = np.dot(np.linalg.inv(D - L), b)

    eigvalues, eigvectors = np.linalg.eig(T_g)
    radio_espectral = np.max(np.abs(eigvalues))

    if radio_espectral >= 1:
        print("El método de Gauss-Seidel no converge")
        return None, None

    error = 1
    iteraciones = 0

    while error > tol:
        iteraciones += 1
        x_new = np.dot(T_g, x0) + C_g
        error = np.max(np.abs(x_new - x0))
        x0 = x_new

    return x_new, iteraciones

In [2]:
A = np.array([[10, -3, 5], [-2, -13, 7], [4, -8, 15]])

b = np.array([12, 23, 14])

x0 = np.ones_like(b)

tol = 1e-4

tiempo_inicial = time.time()

x_new, iteraciones = gauss_seidel_matrices(A, b, x0, tol)

tiempo_final = time.time()

if x_new is not None:
    print("Solución encontrada:")
    print(x_new)

print("El tiempo de ejecución fue:", tiempo_final - tiempo_inicial, "segundos")
print("El número de iteraciones fue:", iteraciones)

Solución encontrada:
[ 0.76553046 -2.09638485 -0.38888004]
El tiempo de ejecución fue: 0.0228574275970459 segundos
El número de iteraciones fue: 8


In [12]:
import numpy as np

A = np.array([[10,-3,5],[-2,-13,7],[4,-8,15]], float)
b = np.array([12,23,14], float)
xo = np.ones_like(b)
tol = 1e-6
nMax = 100

def Gauss_seidel_sumas(A,b,xo,tol):
    n = len(b)
    error = 1
    while error > tol:
        x_new = np.zeros_like(b)
        for i in range(n):
            sum1 = 0
            for j in range(i):
                sum1 += A[i,j]*x_new[j]
            sum2 = 0
            for j in range(i+1, n):
                sum2 += A[i,j] * xo[j]
            x_new[i] = (b[i]-sum1-sum2)/A[i,i]
        error = max(abs(x_new-xo))
        xo = x_new
        print(x_new, error)

Gauss_seidel_sumas(A,b,xo,tol)

[ 1.         -1.38461538 -0.07179487] 2.3846153846153846
[ 0.82051282 -1.93412229 -0.31700197] 0.5495069033530573
[ 0.7782643  -2.05965711 -0.3726876 ] 0.12553482020937645
[ 0.76844667 -2.08813127 -0.38525579] 0.028474166404071077
[ 0.76618851 -2.09455135 -0.38807766] 0.006420076866517466
[ 0.76567342 -2.09599157 -0.38870842] 0.0014402216840703197
[ 0.76555674 -2.09631326 -0.38884887] 0.0003216887729795559
[ 0.76553046 -2.09638485 -0.38888004] 7.158424853903611e-05
[ 0.76552457 -2.09640072 -0.38888694] 1.5877633018579473e-05
[ 0.76552325 -2.09640424 -0.38888846] 3.5116953172042997e-06
[ 0.76552296 -2.09640501 -0.38888879] 7.747446320038875e-07
