In [48]:
import numpy as np
import time

A = np.array([[10,-3,5],[-2,-13,7],[4,-8,15]], float)
b = np.array([12,23,14], float)
def Jacobi_matrices(A, b, x0, tol):
    # Declarar el valor inicial
    #x0 = np.ones_like(b)
    D = np.diag(np.diag(A))
    U = D - np.triu(A)
    L = D - np.tril(A)
    # Matrix Tjacobi
    T_jab = np.dot(np.linalg.inv(D), L+U)
    C_jac = np.dot(np.linalg.inv(D), b)
    eigvalues, eigvectores = np.linalg.eig(T_jab)
    radio_espectral = max(abs(eigvalues))
    if radio_espectral >= 1:
        print('El sistema iterativo no converge para ningun valor inicial')
        return None, None, None
    else:
        count = 0
        error = 1
        tiempo_inicial = time.time()
        while error > tol:
            count += 1
            x1 = np.dot(T_jab, x0) + C_jac
            #print(x1)
            error = max(abs(x1-x0))
            if count == 3:
                print(x1)
            x0 = x1
        tiempo_final = time.time()
        tiempo_total = tiempo_final - tiempo_inicial
        return x1, count, tiempo_total


In [49]:
A = np.array([[3,-1,0,0],[-1,-3,1,0],[0,1,3,-1],[0,0,-1,-3]], float)
b = np.array([12,12,10,10], float)
x0 = np.array([1,0,1,0])
x1, count, tiempo_total = Jacobi_matrices(A, b, x0, 1e-6)
#print(x1)
print(count)
print(tiempo_total)



[ 2.59259259 -3.74074074  3.25925926 -4.48148148]
24
0.0008423328399658203


In [53]:
A = np.array([[10,-3,5],[-2,-13,7],[4,-8,15]], float)
b = np.array([12,23,14], float)
n = len(b)
print(A)
for i in range(n):
    aux = sum(abs(A[i,0:n]) - abs(A[i,i]))
    if abs(A[i,i]) >= aux:
        print('ok')
    

[[ 10.  -3.   5.]
 [ -2. -13.   7.]
 [  4.  -8.  15.]]
ok
ok
ok
