In [13]:
import numpy as np

A = np.array([[-3,2,1],[6,-8,-2],[1,-1,-2]], float)
b = np.array([2,1,3], float)
n = len(b)

for i in range(n):
    for j in range(i+1, n):
        factor = A[j,i] / A[i,i]
        print(factor)
        A[j, i:n] = A[j, i:n] - factor*A[i, i:n]
        print(A)

-2.0
[[-3.  2.  1.]
 [ 0. -4.  0.]
 [ 1. -1. -2.]]
-0.3333333333333333
[[-3.          2.          1.        ]
 [ 0.         -4.          0.        ]
 [ 0.         -0.33333333 -1.66666667]]
0.08333333333333334
[[-3.          2.          1.        ]
 [ 0.         -4.          0.        ]
 [ 0.          0.         -1.66666667]]
